language: ruby
rvm:
  - 1.9.3

env:
  - DB=sqlite

script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec
  - RAILS_ENV=test bundle exec rake spec --tag slow_tests
services:
  - redis-server



